import { NextRequest, NextResponse } from 'next/server';
import { callClaudeWithRetry } from '@/lib/ai';

export async function POST(request: NextRequest) {
  try {
    const { pdfBase64, filename } = await request.json();

    if (!pdfBase64) {
      return NextResponse.json({ error: 'Missing PDF data' }, { status: 400 });
    }

    const response = await callClaudeWithRetry(
      `Analyze this Australian energy regulatory document and generate a concise, descriptive title.

INSTRUCTIONS:
1. Identify the source (AEMO, AEMC, AER, ESC, etc.)
2. Identify the document type (Procedure, Rule, Guideline, etc.)
3. Extract the main topic/subject matter
4. Generate a title in this format: "[Source] [Type]: [Brief Description]"

EXAMPLES:
- "AEMO Procedure: MSATS Standing Data Updates"
- "AEMC Rule: Demand Response Mechanism"
- "AER Guideline: Network Revenue Requirements"
- "ESC Victoria: Energy Retail Code Amendments"

RESPOND WITH ONLY THE TITLE (no explanation, no markdown, just the title text).

If you cannot determine source/type from the content, use: "Regulatory Document: [Main Topic]"`,
      pdfBase64,
      500
    );

    const title = response.text.trim();

    return NextResponse.json({ 
      title,
      autoGenerated: true,
      cost: response.inputTokens * 0.000003 + response.outputTokens * 0.000015
    });

  } catch (error: any) {
    console.error('[Auto-Title] Error:', error.message);
    
    const fallbackTitle = `Regulatory Document - ${new Date().toLocaleDateString('en-AU')}`;
    
    return NextResponse.json({ 
      title: fallbackTitle,
      autoGenerated: true,
      cost: 0,
      error: 'Used fallback title'
    }, { status: 200 });
  }
}
